webserver:
  port: 3000
  url: "http://localhost:3000"

hostname:
  api: "api.localhost"
  website: "localhost"

# Use virtual hosts for multiple hostnames, if true the engine will also require
# an entry in "/etc/hosts" of: 127.0.0.1  api.localhost
usevhosts: true

# Multiple Nodes running concurently.
multipleNodes: false

# Google Analytics key
ga: "UA-XXXXX-X"

logger:
  # Log Levels:
  # SEVERE: 1000
  # WARN:   800
  # INFO:   600
  # FINE:   400
  # FINER:  200
  # FINEST: 100
  level: 100
  syslog: false
  file: false
  console: true
  filename: "./logs/app.log"

mongo:
  hostname: localhost
  database: app
  testDatabase: apptest
  # Attempt to reconnect interval in ms.
  reconnectTime: 500

redis:
  namespace: "app:"
  main:
    host: "localhost"
    port: 6379
  sessionWebsite:
    # https://github.com/visionmedia/connect-redis#options
    host: "localhost"
    port: 6379
    prefix: "appSessionWeb:"
  sessionApi:
    host: "localhost"
    port: 6379
    prefix: "appSessionApi:"
  kansas:
    port: 6379
    host: "localhost"
    pass: ""
  idify:
    port: 6379
    host: "localhost"
    pass: ""

cookies:
  website:
    # domain: ".localhost"
    name: 'app'
    session:
      secret: "zzz"
      maxAge: null
  api:
    # domain: ".api.localhost"
    name: 'api'
    session:
      secret: "xxx"
      maxAge: null


users:
  # Durations in milliseconds:
  # 1 day:      86400000
  # 1 week:    604800000
  # 1 month:  2592000000
  # 3 months: 7776000000
  emailConfirmationExpires: 7776000000
  passwordResetExpires: 604800000

crypto:
  salt: "zzz"

mandrill:
  apikey: "xxx"
  apikeyStub: "xxx"

test:
  hostname: "localhost"
  port: 3000
  apiPort: 3001

# This is about the API websocket server
websocket:
  # The time to wait for a challenge to complete, in milliseconds.
  challengeTimeout: 6000

  # The timeout for the client, when it closes the connection it still X amounts
  # of seconds to do re open of the connection. This value is sent to the
  # client after a successful handshake.
  closeTimeout: 60

  # The begin point where Socket.IO starts looking for incoming connections.
  # This should be the same between the client and the server.
  # WARNING: do not change this value or socket.io breaks (!)
  resource: "socket.io"
